version: '3.8'

networks:
  internal:

volumes:
  web-log:
  psql-data:

services:
  dragonball-web:
    container_name: dragonball-web
    build:
      context: .
      dockerfile: ./Dockerfile.web
    environment:
      SCOPE: "local"
    ports:
    - "8080:8080"
    volumes:
    - web-log:/conf/logs/
    networks:
      internal:
    depends_on:
      - dragonball-postgresql

  dragonball-postgresql:
    container_name: dragonball-postgresql
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: 'localdb'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'local'
    ports:
    - "5432:5432"
    volumes:
    - "psql-data:/var/lib/postgresql/data"
    - "./conf/tools/master.conf:/etc/postgresql/postgresql.conf"
    - "./conf/tools/master-pg_hba.conf:/etc/postgresql/pg_hba.conf"
    - "./conf/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    networks:
      internal:
